services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  celery:
    build: .
    volumes: 
    - ./:/app/
    env_file:
      - .env.dev
    command: celery -A mycoffee worker -l INFO
    
    depends_on:
      - web

volumes:
  postgres_data:
  rabbitmq_data:
