# Generated by Django 4.2.7 on 2023-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_pdf_file_alter_report_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='requested_by',
        ),
        migrations.AlterField(
            model_name='report',
            name='stage',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Done', 'Done')], default='Preparing', max_length=100),
        ),
    ]
