# Generated by Django 4.2.5 on 2023-11-06 06:12

from django.db import migrations, models
import orders.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=orders.fields.RandomField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=orders.fields.RandomField(primary_key=True, serialize=False),
        ),
    ]
