# Generated by Django 4.2.5 on 2023-11-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id_alter_order_status_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending'),
        ),
    ]
