# Generated by Django 4.2.5 on 2023-11-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
    ]
