# Generated by Django 4.2.5 on 2023-10-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
